name: zenodraft
description: 'Draft a deposition on Zenodo or Zenodo Sandbox'
inputs:
  args:
    description: 'arguments to zenodraft executable'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}