name: zenodraft
branding:
  icon: 'upload-cloud'
  color: 'green'
description: 'Draft a deposition on Zenodo or Zenodo Sandbox'
inputs:
  collection:
    description: 'Create the new deposition as a new version in this collection.'
    required: false
    default: ''
  compression:
    description: 'Which compression to use when making a snapshot of the entire repository (precludes use of argument filenames).'
    required: false
    default: 'zip'
  filenames:
    description: 'List of space-separated filenames that should be upload separately instead of the default behavior of uploading a snapshot of the entire repository as an archive (precludes use of argument compression).'
    required: false
    default: ''
  metadata:
    description: 'Filename that contains the metadata for the deposition in Zenodo metadata format.'
    required: false
    default: ''
  publish:
    description: 'Publish the deposition. Beware, deposition contents cannot be changed once the deposition has been published.'
    required: false
    default: false
  sandbox:
    description: 'Whether the deposition should be created on Zenodo Sandbox instead of Zenodo.'
    required: false
    default: true
runs:
  using: 'node12'
  main: 'lib/index.js'
