name: zenodraft
description: 'Draft a deposition on Zenodo or Zenodo Sandbox'
inputs:
  sandbox:
    description: 'Whether in Zenodo Sandbox.'
    required: false
    default: true
  in-collection:
    description: 'Create the new deposition in this collection.'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sandbox }}
    - ${{ inputs.in-collection }}
