name: zenodraft
description: 'Draft a deposition on Zenodo or Zenodo Sandbox'
inputs:
  args:
    description: 'Arguments to the zenodraft executable.'
    required: false
    default: '--help'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
