name: testing
on:
  workflow_dispatch:

jobs:

  no-args:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2      
        - name: Test without any input arguments / creating a draft in a new collection
          env:
            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}        
          uses: ./

  in-collection:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2      
        - name: Test creating a draft in an existing collection
          env:
            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}        
          uses: ./
          with:
            collection: '831247'
            metadata: .github/.zenodo-in-collection.json


  with-filenames:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - run: echo "txt contents" > test.txt
        - run: echo "pdf contents" > test.pdf
        - name: Test with metadata
          env:
            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}        
          uses: ./
            with:
              filenames: test.txt test.pdf
              metadata: .github/.zenodo-with-filenames.json

  with-compression-tar-gz:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: Test with metadata
          env:
            ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}        
          uses: ./
            with:
              compression: tar.gz
              metadata: .github/.zenodo-with-compression-tar-gz.json