name: unittests
on:
  pull_request:

jobs:

  unit:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v2
        - name: run unit tests with jest
          run: npm run test 

